---
name: Checks

#Specify trigger action
on: [push]

#Specifying jobs to run when triggered
jobs:
  test-lint:
    name: Test and lint
      runs-on: ubuntu-20.04
      #Steps to execute for Test and lint job
      steps: 
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
        - name: Lint
          run: docker-compose run --rm app sh -c "flake8"